### ISSUE TITLE
Feature request for: /web3-data-api/evm/reference/get-decoded-wallet-transaction

### ISSUE THREAD

**Issue by Porno77** [MoralisWeb3/docs#156] opened 2023-05-20 08:16 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YosephKS** [comment] 2023-05-22 09:10
Hey @Porno77,

Thanks for reaching out to us 😄 

Can you let me know what the issue is here with /web3-data-api/evm/reference/get-decoded-wallet-transaction?

**Comment by YosephKS** [comment] 2023-05-24 00:06
Hey @Porno77 

I'll be closing this for now since I am not sure what is the scope of the problem or feature request here.

Feel free to create a new issue in the future if you have any suggestions or other feedback.

Have a nice day~

**Closed by YosephKS** 2023-05-24 00:06 UTC
